name: Build NoitaChestFinder

on:
  push:
    branches: [ rewrite-2 ]
  pull_request:
    branches: [ rewrite-2 ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      shell: pwsh
      run: |
        choco install -y llvm cmake ninja
        git clone https://github.com/microsoft/vcpkg
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg install libpng:x64-windows

        echo "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Setup MSVC environment
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        set > msvc_env.txt

    - name: Import MSVC environment into PowerShell
      shell: pwsh
      run: |
        Get-Content msvc_env.txt | ForEach-Object {
          if ($_ -match "^(.*?)=(.*)$") {
            echo "$($_.Split('=')[0])=$($_.Split('=')[1])" >> $env:GITHUB_ENV
          }
        }
      
    - name: cuda-toolkit
        # You may pin to the exact commit or the version.
        # uses: Jimver/cuda-toolkit@1a3c14e26833ccf292b268f9a790fb47dea7b2da
      uses: Jimver/cuda-toolkit@v0.2.28
      with:
        use-local-cache: false
      
                
      
    - name: Build project
      shell: pwsh
      run: |
        echo "Using clang-cl to build..."
        make NoitaChestFinder

    - name: Test build
      shell: pwsh
      run: |
        ./NoitaChestFinder.exe --help || true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: NoitaChestFinder
        path: NoitaChestFinder.exe
